- name: install nginx and run
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present
  
  - name: start nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes


  - name: Collect package facts
    ansible.builtin.package_facts:

  - name: Check if nginx is installed
    debug:
    msg: "Nginx is installed"
    when: "'nginx' in ansible_facts.packages"
