- name: install nginx and run
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
     name: nginx
     state: present
  
  - name: start nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
     
  - name: Check nginx service status
      ansible.builtin.service_facts:

  - name: Show nginx status
    ansible.builtin.debug:
      msg: "✅ Nginx is running and installed."
    when: "'nginx' in ansible_facts.services and ansible_facts.services['nginx'].state == 'running'"

  # - name: check nginx installed or not
  #   ansible.builtin.package_facts:
  #      msg: "✅ Nginx is installed!"
  #      when: "'nginx' in ansible_facts.packages"
  # # - name: Report if Nginx is installed
  #   #ansible.builtin.debug:
     
  # - name: Report if Nginx is NOT installed
  #   ansible.builtin.debug:
  #       msg: "❌ Nginx is NOT installed!"
  #       when: "'nginx' not in ansible_facts.packages"   