- name: variables from files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print the course details
    ansible.builtin.debug:
      msg: course details is : {{course}}, duration :{{ duration }}, student is : {{student}}