- name: install packages
  hosts: local
  connection: local
  tasks:
  - name: print the names
    ansible.builtin.package:
     name: "{{item}}"
     state: installed
    loop:
    - nginx
    - mysql
    - zip